#!/usr/bin/env python3
"""Regenerate executable/<member>/checklist.md files from executable/board.md.

board.md is the single status source. Checklists are generated — never hand-edit them.
Usage:
    python3 executable/tools/sync-checklists.py          # regenerate all checklists
    python3 executable/tools/sync-checklists.py --check  # exit 1 if any checklist is stale
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOARD = ROOT / "board.md"
HEADER = "| ID | Task | Owner | Depends on | Due | Status |"

DoD = """## Definition of done (every task)
- [ ] PR with `[TASK-ID]` title merged · tests green
- [ ] Affected `docs/` file updated in same PR
- [ ] board.md Status set `[x]` · checklist regenerated by kv

---
_Generated by `executable/tools/sync-checklists.py` from [board.md](../board.md) — do not hand-edit._"""


def parse_board() -> list[dict]:
    tasks: list[dict] = []
    section = ""
    for raw in BOARD.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("## "):
            section = line[3:].strip()
            continue
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) != 6 or cells[0] in ("ID", "---") or set(cells[0]) <= set("-"):
            continue
        tid, task, owner, dep, due, status = cells
        if not re.fullmatch(r"[A-Z]+-\d+", tid):
            continue
        tasks.append(
            {
                "id": tid,
                "task": task,
                "owner": owner.lower(),
                "dep": dep,
                "due": due,
                "status": status,
                "section": section,
            }
        )
    return tasks


def render(owner: str, tasks: list[dict]) -> str:
    lines = [
        f"# Checklist — {owner}",
        "",
        f"> Auto-generated from [board.md](../board.md) on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "> Edit status in board.md, not here.",
        "",
    ]
    current_section = None
    for t in sorted(tasks, key=lambda x: (x["due"], x["id"])):
        if t["section"] != current_section:
            current_section = t["section"]
            lines += [f"## {current_section}", ""]
        dep = f" ← needs {t['dep']}" if t["dep"] != "—" else ""
        lines.append(f"- {t['status']} **{t['id']}** · {t['task']} · due {t['due']}{dep}")
    lines += ["", DoD, ""]
    return "\n".join(lines)


def normalize(text: str) -> str:
    """Drop the generation timestamp line so --check compares stable content only."""
    return "\n".join(
        line for line in text.splitlines() if not line.startswith("> Auto-generated")
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    tasks = parse_board()
    if not tasks:
        print(f"error: no tasks parsed from {BOARD}", file=sys.stderr)
        return 1

    by_owner: dict[str, list[dict]] = {}
    for t in tasks:
        by_owner.setdefault(t["owner"], []).append(t)

    stale = []
    for owner, rows in sorted(by_owner.items()):
        target = ROOT / owner / "checklist.md"
        expected = render(owner, rows)
        if args.check:
            actual = target.read_text(encoding="utf-8") if target.exists() else ""
            if normalize(actual) != normalize(expected):
                stale.append(str(target))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8")
            print(f"wrote {target} ({len(rows)} tasks)")

    if args.check:
        if stale:
            print("stale checklists (run: python3 executable/tools/sync-checklists.py):")
            for s in stale:
                print(f"  {s}")
            return 1
        print("all checklists in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
